import type { Project } from "../db/repositories.js";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface GeneratedContextFiles {
  claudeMd: string;
  agentsMd: string;
  cursorRules: string;
  copilotInstructions: string;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function parseJsonArray(raw: string): string[] {
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function formatConstraints(raw: string): string {
  const items = parseJsonArray(raw);
  if (items.length === 0) return "None defined.";
  return items.map((c) => `- ${c}`).join("\n");
}

function deploymentLabel(target: string): string {
  const map: Record<string, string> = {
    vercel: "Vercel",
    railway: "Railway",
    flyio: "Fly.io",
    aws: "AWS",
    docker: "Docker / VPS",
    other: "Other",
    not_decided: "Not decided yet",
  };
  return map[target] ?? target;
}

// ─── Session Instructions ─────────────────────────────────────────────────────

/**
 * Generates the session instructions document — the brief loaded at the start
 * of every AI collaboration session. Eliminates the cold-start problem.
 */
export function generateSessionInstructions(project: Project): string {
  const constraints = formatConstraints(project.constraints);

  return `# Session Instructions — ${project.name}

**Generated by Anvil**
**Developer:** ${project.developerName}

---

## Identity

You are a senior engineer working on **${project.name}** alongside ${project.developerName}.

${project.developerContext ? `**Developer context:** ${project.developerContext}` : ""}

---

## What This Project Is

${project.description}

---

## Architecture

${project.architecture || "Not yet defined. Complete Stage 2 (Full Scope Documentation) to populate this section."}

---

## Tech Stack

${project.stack || "Not yet defined."}

---

## Environment

${project.environment || "Not yet defined."}

**Test command:** \`${project.testCommand}\`

---

## Hard Constraints

These are non-negotiable. Never violate them.

${constraints}

---

## Current State

${project.currentState || "Project is in initial setup. No implementation has begun."}

---

## Deployment Target

${deploymentLabel(project.deploymentTarget)}

---

## Development Workflow

Every increment follows this loop without exception:

1. **Propose** — Explain what will be built, why it matters, and how it fits the architecture. Flag risks before writing any code. No code until confirmed.
2. **Implement** — Deliver production-ready code one component at a time.
3. **Verify** — Run \`${project.testCommand}\`. Share exact results. Fix failures before moving forward.
4. **Commit** — Once all tests are green, commit. Each commit is a verified, working state.
5. **Repeat** — Next step. Continue until all phase objectives are met.

---

## Code Standards

${project.codeStandards || `- TypeScript everywhere. Strict mode enabled.
- Functional components with hooks (no class components).
- All public functions and API endpoints have JSDoc comments.
- Error handling: try/catch with meaningful error messages. Never swallow errors silently.
- No \`any\` types unless absolutely necessary and documented.
- One component per file. Co-locate related files (component + test + types).`}

---

*These instructions are generated by Anvil and update automatically as the project evolves.*
`;
}

// ─── Master Build Document ────────────────────────────────────────────────────

/**
 * Generates the Master Build Document — the single source of truth for the
 * entire project. Architecture, strategy, decisions, constraints.
 */
export function generateMasterDoc(project: Project): string {
  const constraints = formatConstraints(project.constraints);
  const deployment = deploymentLabel(project.deploymentTarget);

  return `# ${project.name} — Master Build Document

**Version:** 1.0
**Developer:** ${project.developerName}
**Generated by Anvil**

---

## 1. Project Overview

${project.description}

---

## 2. Architecture

${project.architecture || "_To be defined in Stage 2 (Full Scope Documentation)._"}

---

## 3. Tech Stack

${project.stack || "_To be defined._"}

---

## 4. Environment

${project.environment || "_To be defined._"}

**Test command:** \`${project.testCommand}\`

---

## 5. Current State

${project.currentState || "_Project is in initial setup. No implementation has begun._"}

---

## 6. Hard Constraints

${constraints}

---

## 7. Deployment Architecture

**Target platform:** ${deployment}

${
  project.deploymentTarget === "not_decided"
    ? `_Deployment target has not been decided yet. Define the following before the final implementation phase:_

- Target platform (Vercel, Railway, Fly.io, AWS, Docker/VPS, other)
- Environment variables and secrets management approach
- CI/CD pipeline (if any)
- Domain and DNS configuration
- Deployment checklist`
    : `_Deployment architecture detail to be completed during Stage 4 (Phase Planning)._

Key decisions to document:
- Environment variables and secrets management
- CI/CD approach
- Domain and DNS
- Deployment checklist`
}

---

## 8. Decision Log

_Architectural and design decisions are recorded here as the project evolves._

| Date | Decision | Rationale | Alternatives Considered |
|------|----------|-----------|------------------------|
| — | — | — | — |

---

## 9. Known Issues & Technical Debt

_Tracked here as they are discovered._

- None at project inception.

---

*This document is the single source of truth for ${project.name}. It is updated as the project evolves.*
`;
}

// ─── Context Files ────────────────────────────────────────────────────────────

/**
 * Generates context files in all major AI tool formats from the same
 * project data. One source, four outputs.
 */
export function generateContextFiles(
  project: Project,
  existingContent?: Partial<GeneratedContextFiles>
): GeneratedContextFiles {
  const constraints = formatConstraints(project.constraints);

  const coreContext = `## Project: ${project.name}

${project.description}

## Developer
${project.developerName}${project.developerContext ? ` — ${project.developerContext}` : ""}

## Architecture
${project.architecture || "Not yet defined."}

## Tech Stack
${project.stack || "Not yet defined."}

## Hard Constraints
${constraints}

## Test Command
\`${project.testCommand}\`

## Development Workflow
Always propose before implementing. Run tests after every change. Never move forward on a failing test.`;

  const claudeMd = mergeWithExisting(
    `# ${project.name} — Claude Instructions

${coreContext}

## Environment
${project.environment || "Not yet defined."}

## Current State
${project.currentState || "Initial setup. No implementation has begun."}
`,
    existingContent?.claudeMd
  );

  const agentsMd = mergeWithExisting(
    `# ${project.name}

${coreContext}
`,
    existingContent?.agentsMd
  );

  const cursorRules = mergeWithExisting(
    `# ${project.name} Cursor Rules

${project.description}

## Stack
${project.stack || "Not yet defined."}

## Constraints
${constraints}

## Workflow
Propose before implementing. Test after every change. No forward progress on failing tests.

## Test Command
${project.testCommand}
`,
    existingContent?.cursorRules
  );

  const copilotInstructions = mergeWithExisting(
    `# Copilot Instructions — ${project.name}

${project.description}

## Architecture
${project.architecture || "Not yet defined."}

## Stack
${project.stack || "Not yet defined."}

## Rules
${constraints}
`,
    existingContent?.copilotInstructions
  );

  return { claudeMd, agentsMd, cursorRules, copilotInstructions };
}

// ─── Merge helper ─────────────────────────────────────────────────────────────

/**
 * Merges Anvil-generated content with existing developer-written content.
 * Existing content appended under a separator so neither is lost.
 */
function mergeWithExisting(generated: string, existing?: string): string {
  if (!existing || !existing.trim()) return generated;
  return `${generated}
---

## Existing Project Context (imported)

${existing.trim()}
`;
}
